services:
  comments:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 comments_app.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - comments_db:$PGDATA

  redis:
    image: "redis:alpine"

volumes:
  comments_db:
