# Generated by Django 5.0.6 on 2024-05-20 12:44

import comment.models
import comment.validators
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[320, 240],
                        upload_to=comment.models.comment_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "gif", "png", "jpeg"],
                                message="Please upload an image of one of these formats 'jpg', 'gif', 'png'",
                            )
                        ],
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to=comment.models.comment_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt", "plain"],
                                message="Please upload an file of this format - 'txt'",
                            ),
                            comment.validators.file_size,
                        ],
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_post_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="comment.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
